# Generated by Django 5.1 on 2024-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
