# Generated by Django 5.1 on 2024-08-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListDRF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='BookListDRF_price_01836c_idx',
        ),
    ]
